package com.yang.petstore.dao;

import com.yang.petstore.dataobject.CartDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon May 06 17:29:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon May 06 17:29:58 CST 2019
     */
    int insert(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon May 06 17:29:58 CST 2019
     */
    int insertSelective(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon May 06 17:29:58 CST 2019
     */
    CartDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon May 06 17:29:58 CST 2019
     */
    int updateByPrimaryKeySelective(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon May 06 17:29:58 CST 2019
     */
    int updateByPrimaryKey(CartDO record);

    CartDO selectByUserIdAndItemId(@Param("userId") Integer UserId,@Param("itemId")Integer itemId);

    int updateMyCart(@Param("userId") Integer userId, @Param("amount")Integer amount);

    List<CartDO> listCart(Integer userId);

    int deleteByItemId(Integer itemId);
}