package com.yang.petstore.dao;

import com.yang.petstore.dataobject.ItemDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 06 10:44:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 06 10:44:44 CST 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 06 10:44:44 CST 2019
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 06 10:44:44 CST 2019
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 06 10:44:44 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 06 10:44:44 CST 2019
     */
    int updateByPrimaryKey(ItemDO record);

    List<ItemDO> listItem();

    List<ItemDO> selectByCategory(int categoty);

    List<ItemDO> selectCat();

    List<ItemDO> selectDog();

    int increaseSales(@Param("id") Integer id, @Param("amount")Integer amount);

    List<ItemDO> selectByKey(@Param(value="key") String key);

    List<ItemDO> selectByPrice(@Param(value="category") int category,@Param(value="lowPrice")int lowPrice,@Param(value="highPrice") int highPrice);

    List<ItemDO> selectBySales();
}