package com.yang.petstore.dataobject;

public class UserAddressDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver_name
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver_phone
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver_province
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private String receiverProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver_city
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private String receiverCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver_district
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private String receiverDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver_address
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver_zip
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    private String receiverZip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver_name
     *
     * @return the value of user_address.receiver_name
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver_name
     *
     * @param receiverName the value for user_address.receiver_name
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver_phone
     *
     * @return the value of user_address.receiver_phone
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver_phone
     *
     * @param receiverPhone the value for user_address.receiver_phone
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver_province
     *
     * @return the value of user_address.receiver_province
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver_province
     *
     * @param receiverProvince the value for user_address.receiver_province
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince == null ? null : receiverProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver_city
     *
     * @return the value of user_address.receiver_city
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver_city
     *
     * @param receiverCity the value for user_address.receiver_city
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver_district
     *
     * @return the value of user_address.receiver_district
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver_district
     *
     * @param receiverDistrict the value for user_address.receiver_district
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver_address
     *
     * @return the value of user_address.receiver_address
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver_address
     *
     * @param receiverAddress the value for user_address.receiver_address
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver_zip
     *
     * @return the value of user_address.receiver_zip
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver_zip
     *
     * @param receiverZip the value for user_address.receiver_zip
     *
     * @mbg.generated Wed May 08 15:09:38 CST 2019
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    @Override
    public String toString() {
        return   receiverProvince +  receiverCity
                + receiverDistrict  +
                receiverAddress;
    }
}